### ISSUE TITLE
LKMPG is now maintained

### ISSUE THREAD

**Issue by jserv** [LukeDSchenk/linux-driver-programming#1]
A fork of The Linux Kernel Module Programming Guide is now maintained, and you can access its LaTeX script along with updated example code for Linux v5.x: https://github.com/sysprog21/lkmpg

Feel free to generate a fresh build of this book and report issues.

**Comment by LukeDSchenk** [comment]
Apologies for the late reply, and thank you so much for sharing this! I was feeling very frustrated working through the old examples but this news has once again sparked my interest. 

I am seriously very touched that you went out of your way to inform me of this. You are a truly wonderful person 🙂.
